title:             Briar Woods MSA
email:             azad.riyaad@gmail.com
description:       Welcome to the official website of the Muslim Student Association of Briar Woods High School!
author:            Briar Woods MSA
baseurl:           "/site"
url:               "http://bwhs-msa.github.io"

# Social Profiles
twitter_username:  BriarWoodsMSA
# github_username:   
# facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
