title:             Briar Woods MSA
email:             azad.riyaad@gmail.com
description:       The Muslim Student Association provides a friendly environment for Muslim and for those who wish to learn abuot Islam, through a wide variety of fun and educational activities and events. Everyone is welcome, and meetings are on Thursdays in Room 406! The Muslim Student Association is sponsored by Ms. Susan Koujak (Room 406).
author:            Briar Woods MSA
baseurl:           "/site"
url:               "https://bwhs-msa.github.io"

# Social Profiles
twitter_username:  BriarWoodsMSA
# github_username:   
# facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
